# Generated by Django 3.2.9 on 2021-11-17 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
